// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Url from "url";
import * as Path from "path";

var Url$1 = {};

var $$__filename = Url.fileURLToPath(import.meta.url);

var $$__dirname = Path.dirname($$__filename);

function readInput(param) {
  return Fs.readFileSync(Path.join($$__dirname, "input.txt"), "utf8");
}

export {
  Url$1 as Url,
  $$__filename ,
  $$__dirname ,
  readInput ,
}
/* __filename Not a pure module */
