// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core from "./Core.bs.js";
import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as Js_option from "rescript/lib/es6/js_option.js";
import * as Caml_splice_call from "rescript/lib/es6/caml_splice_call.js";

function parseInput(param) {
  return Core.readInput(undefined).split("\n\n").map(function (list) {
                return list.split("\n").map(Belt_Int.fromString);
              }).map(function (list) {
              return list.reduce((function (prev, curr) {
                            return prev + Js_option.getExn(curr) | 0;
                          }), 0);
            });
}

function part1(param) {
  return Caml_splice_call.spliceApply(Math.max, [parseInput(undefined)]);
}

function part2(param) {
  return parseInput(undefined).sort(function (a, b) {
                  return b - a | 0;
                }).slice(0, 3).reduce((function (prev, curr) {
                return prev + curr | 0;
              }), 0);
}

export {
  parseInput ,
  part1 ,
  part2 ,
}
/* Core Not a pure module */
